### ISSUE TITLE
react-qiniu 七牛 React 上传组件

### ISSUE THREAD

**Issue by lenage** [qiniu/js-sdk#72]
repo url: https://github.com/lenage/react-qiniu

**Comment by longbai** [comment]
您好，已经放入社区推荐，多谢 :+1:

**Comment by jimjin** [comment]
@lenage @longbai  react-qiniu 官方demo（http://lenage.com/react-qiniu/） 出错了，上传不了了，什么原因： 

Failed to load resource: the server responded with a status of 501 (Method not implemented)
lenage.com/:1 XMLHttpRequest cannot load http://upload.qiniu.com/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://lenage.com' is therefore not allowed access. The response had HTTP status code 501.
2app.js:20undefined
bluebird.js:953Unhandled rejection SuperagentPromiseError: Bad request
    at http://lenage.com/react-qiniu/script.js:25096:18
    at Request.callback (http://lenage.com/react-qiniu/script.js:25963:3)
    at Request.crossDomainError (http://lenage.com/react-qiniu/script.js:25975:8)
    at XMLHttpRequest.xhr.onreadystatechange (http://lenage.com/react-qiniu/script.js:26038:19)
Caused by:  Error: Origin is not allowed by Access-Control-Allow-Origin
    at Request.crossDomainError (http://lenage.com/react-qiniu/script.js:25973:13)
    at XMLHttpRequest.xhr.onreadystatechange (http://lenage.com/react-qiniu/script.js:26038:19)

**Comment by lenage** [comment]
CORS 的问题，我看一下
Jimjin <notifications@github.com>于2016年8月26日 周五11:16写道：

**Comment by lenage** [comment]
@jimjin 我刚才测试了一下，没有发现上传的问题，可以详细描述一下你的使用场景么？
